[General]
Background="Background.jpg"
ScaleImageCropped=true
ScreenWidth=2560
ScreenHeight=1440
MainColor="#d4d0ce"
AccentColor="#a63d4f"
BackgroundColor="#0e0e0e"
OverrideLoginButtonTextColor="#f0ecea"
InterfaceShadowSize=6
InterfaceShadowOpacity=0.6
RoundCorners=12
ScreenPadding=0
Font="JetBrainsMono Nerd Font"
FontSize=11
Locale=""
HourFormat="HH:mm"
DateFormat="dddd, d MMMM yyyy"
TranslateUsernamePlaceholder=true
ForceLastUser=true
ForcePasswordFocus=true
